#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.82.6.

use crate::api::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::rust2dart::IntoIntoDart;
use flutter_rust_bridge::*;
use std::ffi::c_void;
use std::sync::Arc;

// Section: imports

// Section: wire functions

fn wire_parse_srv1__static_method__SubtitlesParser_impl(
    port_: MessagePort,
    raw_subtitles: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, Vec<ParsedSubtitle>, _>(
        WrapInfo {
            debug_name: "parse_srv1__static_method__SubtitlesParser",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_raw_subtitles = raw_subtitles.wire2api();
            move |task_callback| Result::<_, ()>::Ok(SubtitlesParser::parse_srv1(api_raw_subtitles))
        },
    )
}
fn wire_parse_youtube_timed_text__static_method__SubtitlesParser_impl(
    port_: MessagePort,
    raw_subtitles: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, Vec<ParsedSubtitle>, _>(
        WrapInfo {
            debug_name: "parse_youtube_timed_text__static_method__SubtitlesParser",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_raw_subtitles = raw_subtitles.wire2api();
            move |task_callback| {
                Result::<_, ()>::Ok(SubtitlesParser::parse_youtube_timed_text(api_raw_subtitles))
            }
        },
    )
}
// Section: wrapper structs

// Section: static checks

// Section: allocate functions

// Section: related functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        (!self.is_null()).then(|| self.wire2api())
    }
}

impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

// Section: impl IntoDart

impl support::IntoDart for ParsedSubtitle {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.start.into_into_dart().into_dart(),
            self.end.into_into_dart().into_dart(),
            self.text.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for ParsedSubtitle {}
impl rust2dart::IntoIntoDart<ParsedSubtitle> for ParsedSubtitle {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for RustDuration {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.secs.into_into_dart().into_dart(),
            self.millis.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for RustDuration {}
impl rust2dart::IntoIntoDart<RustDuration> for RustDuration {
    fn into_into_dart(self) -> Self {
        self
    }
}

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

#[cfg(not(target_family = "wasm"))]
#[path = "bridge_generated.io.rs"]
mod io;
#[cfg(not(target_family = "wasm"))]
pub use self::io::*;
