import 'package:youtube_explode_dart/youtube_explode_dart.dart';

extension CaptionOriginIdentifier on ClosedCaptionManifest {
  Iterable<ClosedCaptionTrackInfo> get autoGeneratedCaptions =>
      tracks.where((element) => element.isAutoGenerated);
  Iterable<ClosedCaptionTrackInfo> get manuallyGeneratedCaptions =>
      tracks.where((element) => !element.isAutoGenerated);

  bool get containsAutoGenerated => autoGeneratedCaptions.isNotEmpty;
  bool get containsManuallyGenerated => manuallyGeneratedCaptions.isNotEmpty;
}
