import '../../subtitles_parser/subtitles_parser.dart';

typedef SubtitlesEntry = ({
  SubtitlesParser subtitlesParser,
  bool isAutoGenerated
});

typedef SubtitlesBundle = ({
  SubtitlesEntry mainLanguageSubtitles,
  SubtitlesEntry translatedSubtitles,
});
