// ignore_for_file: public_member_api_docs, sort_constructors_first
import 'package:flutter/foundation.dart';

@immutable
class ScrapedSubtitles {
  const ScrapedSubtitles({
    required this.subtitles,
    required this.isAutoGenerated,
  });
  final String subtitles;
  final bool isAutoGenerated;

  @override
  String toString() =>
      'ScrapedSubtitles(subtitles: $subtitles, isAutoGenerated: $isAutoGenerated)';

  @override
  bool operator ==(covariant ScrapedSubtitles other) {
    if (identical(this, other)) return true;

    return other.subtitles == subtitles &&
        other.isAutoGenerated == isAutoGenerated;
  }

  @override
  int get hashCode => subtitles.hashCode ^ isAutoGenerated.hashCode;
}
