// ignore_for_file: public_member_api_docs, sort_constructors_first
import 'package:flutter/foundation.dart';
import 'package:languages/languages.dart';

@immutable
class CaptionsInfo {
  final String videoId;
  final bool isAutoGenerated;
  final Language? language;

  const CaptionsInfo({
    required this.videoId,
    required this.isAutoGenerated,
    required this.language,
  });

  @override
  String toString() =>
      'CaptionsInfo(videoId: $videoId, isAutoGenerated: $isAutoGenerated, language: $language)';

  @override
  bool operator ==(covariant CaptionsInfo other) {
    if (identical(this, other)) return true;

    return other.videoId == videoId &&
        other.isAutoGenerated == isAutoGenerated &&
        other.language == language;
  }

  @override
  int get hashCode =>
      videoId.hashCode ^ isAutoGenerated.hashCode ^ language.hashCode;
}
