[package]
name = "readability"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
cargo-ndk = "3.2.0"
flutter_rust_bridge = "1.82.6"
flutter_rust_bridge_codegen = "1.82.6"
unicode-segmentation = "1.10.1"
regex = "1.10.1"
scraper = "0.17.1"
lazy_static = "1.4.0"
rayon = "1.8.0"
serde_json = "1.0.111"
[dependencies.nnsplit]
version = "0.5.9"
features = ["model-loader", "tract-backend"]

