workspace = { members = ["libs/readability_implementation", "libs/readability_implementation/example"] }
[package]
name = "readability"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
cargo-ndk = "3.2.0"
flutter_rust_bridge = "1.82.6"
flutter_rust_bridge_codegen = "1.82.6"
serde = "1.0.196"
serde_json = "1.0.112"
[dependencies.readability_implementation]
version = "0.1.0"
path = "libs\\readability_implementation"




