import 'package:youtube_subtitles_scraper/src/abstract/cache_manager.dart';

extension SourcesCountManager on CacheManager {
  static const int _defaultMaxSourcesCount = 50;
  Future<void> limitSourcesCount(
      {int maxSourceCount = _defaultMaxSourcesCount}) async {
    final sources = await retrieveSources();
    if (sources.length > maxSourceCount) {
      sources.toList().sublist(maxSourceCount).forEach((source) async {
        await clearSources(
          videoId: source.info.videoId,
          isAutoGenerated: source.info.isAutoGenerated,
          language: source.info.language?.name,
        );
      });
    }
  }
}
