// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.21.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'simple/readability_score.dart';
import 'simple/readability_score/text_metrics.dart';

ReadabilityScore calculateSubtitlesReadability(
        {required String text, dynamic hint}) =>
    RustLib.instance.api.calculateSubtitlesReadability(text: text, hint: hint);

int countSyllables({required String text, dynamic hint}) =>
    RustLib.instance.api.countSyllables(text: text, hint: hint);

String greeet({required String name, dynamic hint}) =>
    RustLib.instance.api.greeet(name: name, hint: hint);
