[package]
name = "rust_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.0.0-dev.21"
unicode-segmentation = "1.10.1"
regex = "1.10.1"
scraper = "0.17.1"
lazy_static = "1.4.0"
rayon = "1.8.0"
[dependencies.nnsplit]
version = "0.5.9"
features = ["model-loader", "tract-backend"]