// if you forget where the dynamic library is located in the apk,
// look at the build warnings

// This file initializes the dynamic library and connects it with the stub
// generated by flutter_rust_bridge_codegen.

import 'dart:ffi';
import 'dart:io';

import 'package:readability/src/rust_bridge/bridge.dart';

// Re-export the bridge so it is only necessary to import this file.
export 'bridge.dart';
import 'dart:io' as io;

const _base = 'readability';

// On MacOS, the dynamic library is not bundled with the binary,
// but rather directly **linked** against the binary.
final _dylibPath = io.Platform.isWindows ? '$_base.dll' : 'lib$_base.so';

final _dylib = Platform.isIOS
    ? DynamicLibrary.process()
    : Platform.isMacOS
        ? DynamicLibrary.executable()
        : DynamicLibrary.open(_dylibPath);

final rustApi = ReadabilityImpl(_dylib);
