import 'package:youtube_subtitles_scraper/src/data/models/scraped_subtitles.dart';
import 'package:youtube_subtitles_scraper/src/data/models/source_captions.dart';

abstract class CacheManager {
  Future<void> cacheSubtitles(ScrapedSubtitles subtitles);
  Future<void> cacheSourceCaptions(SourceCaptions sourceCaptions);

  Future<Iterable<ScrapedSubtitles>?> retrieveSubtitles(
      {String? videoId, String? language});
  Future<Iterable<SourceCaptions>?> retrieveSources(
      {String? videoId, String? language});

  Future<void> clearSubtitlesCache();
  Future<void> clearSources({String? videoId, bool? isAutoGenerated});
}
