import 'package:youtube_subtitles_scraper/src/models/scraped_captions.dart';
import 'package:youtube_subtitles_scraper/src/models/source_captions.dart';

abstract class CacheManager {
  Future<void> cacheCaptions(ScrapedCaptions subtitles);
  Future<void> cacheSourceCaptions(SourceCaptions sourceCaptions);

  Future<Iterable<ScrapedCaptions>> retrieveSubtitles(
      {String? videoId, String? language});
  Future<Iterable<SourceCaptions>> retrieveSources(
      {String? videoId, String? language});

  Future<void> clearSubtitlesCache();
  Future<void> clearSources({String? videoId, bool? isAutoGenerated});
}
