import 'package:youtube_subtitles_scraper/src/data/scraped_subtitles.dart';
import 'package:youtube_subtitles_scraper/src/data/source_subtitles.dart';

abstract class CacheManager {
  Future<void> cacheSubtitles({
    required String subtitles,
    required String videoId,
    required String language,
    required bool isSubtitlesAutoGenerated,
  });
  Future<Iterable<ScrapedSubtitles>?> retrieveSubtitles({
    required String videoId,
    required String language,
  });

  Future<void> clearSubtitlesCache();

  Future<void> cacheSubtitlesSourceCaptions({
    required String videoId,
    required List<SourceCaptions> sourceCaptions,
  });

  Future<List<SourceCaptions>?> retrieveSubtitlesSourceUrls(
      {required String videoId});
}
