// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.21.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'readability_score/text_metrics.dart';

class ReadabilityScore {
  final TextMetrics rawMetrics;
  final double lixIndex;
  final double rixIndex;
  final double fleschKincaidGrade;
  final double automatedReadabilityIndex;
  final double colemanLiauIndex;
  final double gunningFoxIndex;
  final double smogIndex;

  const ReadabilityScore({
    required this.rawMetrics,
    required this.lixIndex,
    required this.rixIndex,
    required this.fleschKincaidGrade,
    required this.automatedReadabilityIndex,
    required this.colemanLiauIndex,
    required this.gunningFoxIndex,
    required this.smogIndex,
  });

  static Future<Self> newReadabilityScore({required Str text, dynamic hint}) =>
      RustLib.instance.api.readabilityScoreNew(text: text, hint: hint);

  @override
  int get hashCode =>
      rawMetrics.hashCode ^
      lixIndex.hashCode ^
      rixIndex.hashCode ^
      fleschKincaidGrade.hashCode ^
      automatedReadabilityIndex.hashCode ^
      colemanLiauIndex.hashCode ^
      gunningFoxIndex.hashCode ^
      smogIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadabilityScore &&
          runtimeType == other.runtimeType &&
          rawMetrics == other.rawMetrics &&
          lixIndex == other.lixIndex &&
          rixIndex == other.rixIndex &&
          fleschKincaidGrade == other.fleschKincaidGrade &&
          automatedReadabilityIndex == other.automatedReadabilityIndex &&
          colemanLiauIndex == other.colemanLiauIndex &&
          gunningFoxIndex == other.gunningFoxIndex &&
          smogIndex == other.smogIndex;
}
