// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.21.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'readability_score/text_metrics.dart';

class SyllableCounter {
  final bool debug;
  final Str vowels;
  final List<Str> specials;
  final List<Str> specialsExceptEnd;

  const SyllableCounter({
    required this.debug,
    required this.vowels,
    required this.specials,
    required this.specialsExceptEnd,
  });

  Future<int> count({required Str word, dynamic hint}) =>
      RustLib.instance.api.syllableCounterCount(
        that: this,
        word: word,
      );

  static Future<Self> newSyllableCounter({dynamic hint}) =>
      RustLib.instance.api.syllableCounterNew(hint: hint);

  @override
  int get hashCode =>
      debug.hashCode ^
      vowels.hashCode ^
      specials.hashCode ^
      specialsExceptEnd.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyllableCounter &&
          runtimeType == other.runtimeType &&
          debug == other.debug &&
          vowels == other.vowels &&
          specials == other.specials &&
          specialsExceptEnd == other.specialsExceptEnd;
}
