[package]
name = "readability"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
cargo-ndk = "3.2.0"
flutter_rust_bridge = "1.78.0"
regex = "1.8.4"
unicode-segmentation = "1.10.1"
