const String subtitlesDbName = 'subtitles.db';
const String subtitlesTable = 'subtitles';
const String videoIdColumn = 'video_id';
const String subtitlesColumn = 'subtitles';
const String subtitlesLanguageColumn = 'language';
const String isSubtitleAutoGeneratedColumn = 'is_auto_generated';

const String createSubtitlesTableCommand =
    '''CREATE TABLE IF NOT EXISTS $subtitlesTable(
   $videoIdColumn TEXT NOT NULL,
   $subtitlesColumn TEXT NOT NULL,
   $subtitlesLanguageColumn TEXT NOT NULL,
   $isSubtitleAutoGeneratedColumn BOOLEAN NOT NULL CHECK ($isSubtitleAutoGeneratedColumn IN (0, 1))
)''';
