import 'package:flutter/material.dart';
import 'package:youtube_subtitles_scraper/youtube_subtitles_scraper.dart';

import 'cached_captions_info.dart';
import 'captions_type.dart';

@immutable
final class CachedCaptions extends ScrapedCaptions {
  final CachedCaptionsInfo _info;
  @override
  CachedCaptionsInfo get info => _info;
  const CachedCaptions({
    required super.subtitles,
    required CachedCaptionsInfo info,
  })  : _info = info,
        super(info: info);

  CachedCaptions.fromScrapedCaptions(ScrapedCaptions captions)
      : _info = CachedCaptionsInfo(
          videoId: captions.info.videoId,
          type: captions.info.isAutoGenerated
              ? CaptionsType.youTubeAutoGenerated
              : CaptionsType.youTubeUserGenerated,
          language: captions.info.language,
        ),
        super(subtitles: captions.subtitles, info: captions.info);
}
