import 'package:youtube_subtitles_scraper/youtube_subtitles_scraper.dart';

import 'cached_captions_info.dart';
import 'captions_type.dart';

final class CachedSourceCaptions extends SourceCaptions {
  final CachedCaptionsInfo _info;
  @override
  CachedCaptionsInfo get info => _info;
  final DateTime? cacheCreationDate;
  const CachedSourceCaptions({
    required super.uri,
    required CachedCaptionsInfo info,
    required this.cacheCreationDate,
  })  : _info = info,
        super(info: info);

  CachedSourceCaptions.fromSourceCaptions(
    SourceCaptions sourceCaptions, {
    DateTime? createdAt,
  })  : _info = CachedCaptionsInfo(
          videoId: sourceCaptions.info.videoId,
          type: sourceCaptions.info.isAutoGenerated
              ? CaptionsType.youTubeAutoGenerated
              : CaptionsType.youTubeUserGenerated,
          language: sourceCaptions.info.language,
        ),
        cacheCreationDate = createdAt,
        super(uri: sourceCaptions.uri, info: sourceCaptions.info);
}
