import 'package:flutter/material.dart';
import 'package:lang_tube/models/subtitles/cached_captions_info.dart';
import 'package:lang_tube/models/subtitles/captions_type.dart';
import 'package:youtube_subtitles_scraper/youtube_subtitles_scraper.dart';

@immutable
final class CachedSubtitles extends ScrapedCaptions {
  final CachedCaptionsInfo _info;
  @override
  CachedCaptionsInfo get info => _info;
  const CachedSubtitles({
    required super.subtitles,
    required CachedCaptionsInfo info,
  })  : _info = info,
        super(info: info);

  CachedSubtitles.fromScrapedCaptions(ScrapedCaptions captions)
      : _info = CachedCaptionsInfo(
          videoId: captions.info.videoId,
          type: captions.info.isAutoGenerated
              ? CaptionsType.youTubeAutoGenerated
              : CaptionsType.youTubeUserGenerated,
          language: captions.info.language,
        ),
        super(subtitles: captions.subtitles, info: captions.info);
}
