import 'package:core_utils/core_utils.dart';
import 'package:flutter/material.dart';
import 'package:lang_tube/crud/subtitles_cache_manager/constants.dart';
import 'package:youtube_subtitles_scraper/youtube_subtitles_scraper.dart';

import '../../crud/subtitles_cache_manager/utils.dart';

@immutable
final class CachedSubtitles extends ScrapedSubtitles {
  final DateTime? cacheCreationDate;
  const CachedSubtitles({
    required super.subtitles,
    required super.isAutoGenerated,
    required super.videoId,
    required super.language,
    required this.cacheCreationDate,
  });
  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      subtitlesColumn: subtitles.toJson(),
      isSubtitleAutoGeneratedColumn: isAutoGenerated.toInt(),
      videoIdColumn: videoId,
      subtitlesLanguageColumn: language?.name ?? 'unkown'
    };
  }

  CachedSubtitles.fromMap(Map<String, dynamic> map)
      : cacheCreationDate = DateTime.tryParse(map[subtitlesCacheDate]),
        super(
          subtitles: ParsedSubtitlesJsonifier.fromJson(map[subtitlesColumn]),
          isAutoGenerated: (map[isSubtitleAutoGeneratedColumn] as int).toBool(),
          videoId: map[videoIdColumn] as String,
          language: map[subtitlesLanguageColumn] as String,
        );
}
