import 'dart:collection';

import 'package:floor/floor.dart';

import '../../../models/subtitles/captions_type.dart';

class CaptionsTypeStringifier extends TypeConverter<CaptionsType, String> {
  static final _map = HashMap.from({
    CaptionsType.youTubeAutoGenerated: 'youTubeAutoGenerated',
    CaptionsType.youTubeUserGenerated: 'youTubeGenerated',
    CaptionsType.userUploaded: 'manuallyGenerated',
  });

  @override
  CaptionsType decode(String databaseValue) {
    return _map.entries.firstWhere((entry) => entry.value == databaseValue).key;
  }

  @override
  String encode(CaptionsType value) {
    return _map[value]!;
  }
}
