import 'dart:developer';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:lang_tube/youtube_video_player/utils/subtitles_player/utils/subtitle_player_model.dart';
import 'package:lang_tube/youtube_video_player/utils/subtitles_player/views/subtitles_player.dart';
import 'package:lang_tube/youtube_video_player/utils/subtitles_player/utils/subtitles_scraper/subtitles_scraper.dart';
import 'package:lang_tube/youtube_video_player/yotube_video_player_modes/full_screen_youtube_player.dart';

import 'package:youtube_player_flutter/youtube_player_flutter.dart';

abstract class YoutubeVideoPlayerView extends StatelessWidget {
  const YoutubeVideoPlayerView({
    super.key,
    required this.controller,
    required this.subtitlesPlayerProvider,
  });

  factory YoutubeVideoPlayerView.fullScreen(
      {required YoutubePlayerController controller}) {
    return FullScreenYoutubeVideoPlayer(
      controller: controller,
      subtitlesPlayerProvider: subtitlePlayerProvider(
        controller,
      ),
    );
  }

  Widget player({required void Function() onReady}) => YoutubePlayer(
        controller: controller,
        bottomActions: const [],
        topActions: const [],
        onReady: onReady,
        controlsTimeOut: const Duration(days: 1),
      );

  static FutureProvider<ChangeNotifierProvider<SubtitlePlayerModel>>
      subtitlePlayerProvider(YoutubePlayerController controller) {
    return FutureProvider(
      (ref) => SubtitlesScraper.withRandomUserAgent()
          .getSubtitle(
            youtubeVideoId: controller.value.metaData.videoId,
            language: 'English',
            allowAutoGenerated: true,
          )
          .first
          .then(
            (subtitlesParser) => ChangeNotifierProvider(
              (ref) => SubtitlePlayerModel(
                  subtitlesParser: subtitlesParser,
                  youtubePlayerController: controller),
            ),
          ),
    );
  }

  static const double progressBarHandleRadius = 7;
  final YoutubePlayerController controller;
  final FutureProvider<ChangeNotifierProvider<SubtitlePlayerModel>>
      subtitlesPlayerProvider;
  @override
  Widget build(BuildContext context);
}
