import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:lang_tube/youtube_video_player/providers/subtitles_provider.dart';
import 'package:lang_tube/youtube_video_player/providers/youtube_controller_provider.dart';
import 'package:lang_tube/youtube_video_player/components/settings.dart';
import 'package:lang_tube/youtube_video_player/yotube_video_player_modes/full_screen_youtube_player.dart';
import 'package:lang_tube/youtube_video_player/yotube_video_player_modes/portrait_youtube_player.dart';
import 'package:languages/languages.dart';
import 'package:youtube_player_flutter/youtube_player_flutter.dart';

class YoutubeVideoPlayerView extends ConsumerStatefulWidget {
  const YoutubeVideoPlayerView({
    super.key,
  });
  @override
  ConsumerState<ConsumerStatefulWidget> createState() =>
      _YoutubeVideoPlayerViewState();
}

class _YoutubeVideoPlayerViewState
    extends ConsumerState<YoutubeVideoPlayerView> {
  @override
  void initState() {
    SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);
    SystemChrome.setPreferredOrientations([]);

    super.initState();
  }

  @override
  void dispose() {
    SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
    super.dispose();
  }

  // MultiSubtitlesPlayerProvider buildMultiSubtitlesPlayerProvider({
  //   required List<Subtitle>? mainSubtitles,
  //   required List<Subtitle>? translatedSubtitles,
  // }) {
  //   return multiSubtitlesPlayerProvider((
  //     mainSubtitles: mainSubtitles ?? [],
  //     translatedSubtitles: translatedSubtitles ?? [],
  //     playbackPosition:
  //         _youtubePlayerController.where((event) => !event.isDragging).syncMap(
  //               (value) => value.position,
  //             )
  //   ));
  // }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Theme(
      data: theme.copyWith(
        scaffoldBackgroundColor: Colors.grey.shade900,
        iconTheme: theme.iconTheme.copyWith(size: 30),
      ),
      child: Scaffold(
        body: YoutubePlayerBuilder(
          player: YoutubePlayer(
            controller: ref.read(youtubeControllerProvider)!,
            bottomActions: const [],
            topActions: const [],
          ),
          builder: (context, player) {
            return Consumer(
              builder: (context, ref, _) {
                final subtitlesBundles =
                    ref.watch(subtitlesProvider).valueOrNull?.toList();
                final options = subtitlesBundles?.map((subtitlesBundle) => (
                      language: Language.english,
                      isAutoGenerated:
                          subtitlesBundle.mainSubtitles.isAutoGenerated
                    ));
                return OrientationBuilder(
                  builder: (context, orientation) {
                    if (orientation == Orientation.portrait) {
                      return PortraitYoutubePlayer(
                        player: player,
                        subtitlesSettings: const SubtitlesConfig(),
                      );
                    }
                    return FullScreenYoutubeVideoPlayer(
                      player: player,
                    );
                  },
                );
              },
            );
          },
        ),
      ),
    );
  }
}
