import 'dart:convert';
import 'package:lang_tube/utils/int_to_bool.dart';
import 'package:subtitles_parser/subtitles_parser.dart';
import 'package:youtube_subtitles_scraper/youtube_subtitles_scraper.dart';

import '../../utils/bool_to_int.dart';
import 'constants.dart';

extension ParsedSubtitlesJsonifier on List<ParsedSubtitle> {
  // Convert a List<ParsedSubtitle> to a JSON string
  String toJson() => jsonEncode(map((item) => item.toMap()).toList());

  // Convert a JSON string to a List<ParsedSubtitle>
  static List<ParsedSubtitle> fromJson(String jsonString) {
    final List<dynamic> list = jsonDecode(jsonString) as List<dynamic>;
    return list.map((item) => ParsedSubtitle.fromMap(item)).toList();
  }
}

extension ScrapedSubtitlesMapper on ScrapedSubtitles {
  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      subtitlesColumn: subtitles.toJson(),
      isSubtitleAutoGeneratedColumn: boolToInt(isAutoGenerated),
      videoIdColumn: videoId,
      subtitlesLanguageColumn: language?.name ?? 'unkown'
    };
  }

  static ScrapedSubtitles fromMap(Map<String, dynamic> map) {
    return ScrapedSubtitles(
      subtitles: ParsedSubtitlesJsonifier.fromJson(map[subtitlesColumn]),
      isAutoGenerated: intToBool(map[isSubtitleAutoGeneratedColumn] as int),
      videoId: map[videoIdColumn] as String,
      language: map[subtitlesLanguageColumn] as String,
    );
  }
}
