// ignore_for_file: public_member_api_docs, sort_constructors_first
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:lang_tube/subtitles_player/providers/subtitles_cache_provider/database_manager/data/constants.dart';
import 'package:youtube_subtitles_scraper/youtube_subtitles_scraper.dart';

import '../utils/int_to_bool.dart';

@immutable
final class CachedSubtitles extends ScrapedSubtitles {
  const CachedSubtitles({
    required super.subtitles,
    required super.isAutoGenerated,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'subtitles': subtitles,
      'isAutoGenerated': isAutoGenerated,
    };
  }

  factory CachedSubtitles.fromMap(Map<String, dynamic> map) {
    return CachedSubtitles(
      subtitles: map[subtitlesColumn] as String,
      isAutoGenerated: intToBool(
        map[isSubtitleAutoGeneratedColumn],
      ),
    );
  }

  String toJson() => json.encode(toMap());

  factory CachedSubtitles.fromJson(String source) =>
      CachedSubtitles.fromMap(json.decode(source) as Map<String, dynamic>);
}
