import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:lang_tube/youtube_video_player/settings/subtitles_settings/settings.dart';
import 'package:languages/languages.dart';

final subtitlesSelectabilityProvider = StateProvider.autoDispose((ref) => 0);
final translationVisibilityProvider = StateProvider.autoDispose((ref) => true);

class SubtitlesSelectabilityBuilder extends ConsumerWidget {
  const SubtitlesSelectabilityBuilder(
      {super.key, required this.options, required this.builder});

  final List<({Language language, bool isAutoGenerated})> options;
  final Function(SubtitlesSettings settings, int selectedIndex,
      bool shouldShowTranslation) builder;
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return builder(
        SubtitlesSettings(options: options),
        ref.watch(subtitlesSelectabilityProvider),
        ref.watch(translationVisibilityProvider));
  }
}
