workspace = { members = ["example"] }
[package]
name = "subtitles_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
cargo-ndk = "3.2.0"
flutter_rust_bridge = "1.82.3"
flutter_rust_bridge_codegen = "1.82.3"
unicode-segmentation = "1.10.1"
regex = "1.10.1"
scraper = "0.17.1"
lazy_static = "1.4.0"
rayon = "1.8.0"

android_logger =  "0.13.3"
oslog = { version = "0.2.0", optional = true }
log = "0.4.20"
